tophat/RichTextView

.circleci/config.yml
.github/README.md
RichTextView.xcodeproj/xcshareddata/xcschemes/RichTextViewUITests.xcscheme
RichTextView.xcodeproj/xcshareddata/xcschemes/RichTextViewUnitTests.xcscheme
UITests/RichTextViewUITests.swift

- Add CircleCI Integration
- Add build status badge to readme

Add CircleCI Integration

---

RichTextView.xcodeproj/project.pbxproj
Source/Extensions/StringExtension.swift
Source/RichTextParser/LatexParserProtocol.swift
Source/RichWebViewGenerator/RichWebViewGenerator.swift
UnitTests/Extensions/StringExtensionSpec.swift
UnitTests/RichWebViewGenerator/RichWebViewGeneratorSpec.swift

Generate WebViews From Video Tag Input

---

Source/Text Parsing/RichTextParser.swift
UnitTests/Text Parsing/RichTextParserSpec.swift

Strip Code Tags

---

Source/View Generators/RichLabelGenerator.swift
UnitTests/View Generators/RichLabelGeneratorSpec.swift

https://github.com/tophat/RichTextView/issues/13

#13 - Creating label from attributed text

---

RichTextView.xcodeproj/project.pbxproj
Source/Constants/RichDataType.swift
Source/Extensions/NSMutableAttributedStringExtension.swift
Source/RichTextView.swift
Source/Text Parsing/RichTextParser.swift
Source/View Generators/RichLabelGenerator.swift
UnitTests/Extensions/NSMutableAttributedStringExtensionSpec.swift
UnitTests/Text Parsing/RichTextParserSpec.swift
UnitTests/View Generators/RichLabelGeneratorSpec.swift

Handle custom fonts

---

.circleci/config.yml

ci: switch to github releases

---

docs/contribute.md
docs/faq.md
docs/overview.md
website/sidebars.json

```
cd websites
yarn && yarn start
```
Check the docs to see if it looks good.

Docusaurus

---

docs/Style Guide.md

Fixes #58 
- Read Style Guide and make sure it's up to snuff

Add Swift Style Guide

---

.github/README.md
docs/overview.md

Updated Slack badge link to Top Hat Opensource.

Updated Slack badge link.

---

.github/README.md

For free Pull Reminders usage, with permission from @jakebolam. Appreciate the support!

docs: add pull reminders badge

---

website/package.json
website/yarn.lock

Greenkeeper/default/docusaurus 1.7.1

---

.swiftlint.yml
RichTextView.xcodeproj/project.pbxproj
Source/Delegates/RichTextViewDelegate.swift
Source/RichTextView.swift
Source/View Generators/UITextViewGenerator.swift
UnitTests/View Generators/UITextViewGeneratorSpec.swift

feat: Add RichTextView input callback

---

.circleci/config.yml
Podfile
Podfile.lock
RichTextView.podspec
RichTextView.xcodeproj/project.pbxproj
Source/Extensions/NSMutableAttributedStringExtension.swift
UnitTests/Extensions/NSMutableAttributedStringExtensionSpec.swift
UnitTests/Extensions/StringExtensionSpec.swift

fix: trimming issue

---

Example/Podfile.lock
Example/Source/ViewController.swift
Podfile.lock
RichTextView.podspec
Source/Text Parsing/RichTextParser.swift
UnitTests/Text Parsing/RichTextParserSpec.swift

Latest Down seems to break some tests and functionality, this PR is to fix that

fix: Update RichTextView with latest Down

---

.github/README.md
Example/Source/InputOutputModuleView.swift
Example/Source/ViewController.swift
RichTextView.xcodeproj/project.pbxproj
Source/Delegates/RichTextViewDelegate.swift
Source/Extensions/NSMutableAttributedStringExtension.swift
Source/RichTextView.swift
Source/Text Parsing/LatexParserProtocol.swift
Source/Text Parsing/RichTextParser.swift
Source/View Generators/UITextViewGenerator.swift
UITests/RichTextViewUITests.swift
UnitTests/Extensions/NSMutableAttributedStringExtensionSpec.swift
UnitTests/Text Parsing/RichTextParserSpec.swift
UnitTests/View Generators/UITextViewGeneratorSpec.swift

- Add interactive element input type backed by `[interactive-element]` and `[/interactive-element]` tags

feat: Add interactive element input type

---

Source/Text Parsing/RichTextParser.swift

fix: String Extension Crash

---

Source/Text Parsing/RichTextParser.swift

This PR is to add support for multiline LaTeX expressions

feat: Add support for multiline LaTeX expressions

---

Source/Text Parsing/RichTextParser.swift
UnitTests/Text Parsing/RichTextParserSpec.swift

feat: Add underline style to highlighted text

---

Source/Delegates/RichTextViewDelegate.swift
Source/Text Parsing/LatexParserProtocol.swift
Source/View Generators/UITextViewGenerator.swift
UnitTests/View Generators/UITextViewGeneratorSpec.swift

removing unnecessary delegate methods in previous PR

fix: remove unnecessary delegate methods

---

UnitTests/RichTextViewSpec.swift
website/package.json
website/yarn.lock

Update dependencies for "[We found potential security vulnerabilities in your dependencies.](https://github.com/tophat/RichTextView/network/alerts)" warning.

fix: dependency updates

---

.github/README.md

Discontinues the Slack badge, swaps to Discord.

chore: swap slack badge for discord

---

Source/RichTextView.swift
UnitTests/RichTextViewSpec.swift

When input text is updated, accessibility needs to be updated too. 

fix: update accessibility when input text update

---

Example/Podfile.lock
RichTextView.podspec

feat: version bump

---

Example/Podfile.lock
RichTextView.podspec
UnitTests/RichTextViewSpec.swift

feat: 3.2.0 Version Bump

---

Example/Source/ViewController.swift
Source/Extensions/StringExtension.swift
Source/Text Parsing/RichTextParser.swift

fix: stopping replacing U200B by U200D character to stop freezing

---

Example/Podfile.lock
RichTextView.podspec

feat: bumping version to 3.2.2
