tophat/RichTextView

- .circleci/config.yml
This small change makes sure Slack notifications are only sent for failure on master branch.
> Send CircleCI Slack notifications for failures only on master branch

- .github/README.md
They're having storage issues with there stat tracking: see https://github.com/CocoaPods/cocoapods-stats/issues/32
> docs: drop downloads badge until it's accurate

- .circleci/config.yml
Currently we're caching them twice (700mb) which means the download takes 3 minutes. Let's cache them once.
Ci passes
> ci: cache pods once

- .circleci/config.yml
> ci: stop ci running on gh-pages branches

- Source/Text Parsing/RichTextParser.swift
- UnitTests/Text Parsing/RichTextParserSpec.swift
Workaround for https://github.com/iwasrobbed/Down/issues/116
> Parse HTML on main thread

- Example/Podfile
- Example/Podfile.lock
- Example/RichTextView-Example.xcodeproj/project.pbxproj
- Podfile
- Podfile.lock
- RichTextView.podspec
- RichTextView.xcodeproj/project.pbxproj
This PR is to drop support of iOS 9 so RichTextView is compatible with the latest SnapKit.
> fix: Drop iOS 9 Support

- Source/RichTextView.swift
* Added ability to set the background colour of `RichTextView` via:
```
let richTextView = RichTextView()
richTextView.backgroundColor = .red
```
Fixes #96 
In the Example project in the `InputOutputModuleView` try setting the background color of the RichTextView as above, you will see an update in the simulator with the new background color after you re-compile and re-run.
> fix: Enable updating of background color

- Source/Text Parsing/RichTextParser.swift
- UnitTests/Text Parsing/RichTextParserSpec.swift
- Updated `extractInteractiveElement` function to also take in the interactive element's attributes. 
- Navigate to the example project view controller and add this to the private enums Views.subviews:
`InputOutputModuleView(text: """
<sup>[interactive-element id=183d8b0a-db9b-4eda-a0cf-b55bf0a63323]3[/interactive-element]</sup>
""")`
- Run the example project and see a super script interactive element.
> fix: Update RichTextParser.swift to also consume interactive element attributes. 

- Source/Text Parsing/RichTextParser.swift
- UnitTests/Extensions/StringExtensionSpec.swift
Update RichTextParser.swift to have regex for interactive elements not be greedy. 
- Navigate to example project VC and change the private enums to `InputOutputModuleView(text: """ [interactive-element id=1]Some interactive element text[/interactive-element] different text[interactive-element id=1]more interactive element text[/interactive-element] """)`
Run the example project and see a that all interactive elements are shown.
> fix: Update RichTextParser.swift to have regex for interactive elements not be greedy. 

- Source/Text Parsing/RichTextParser.swift
- Navigate to example project VC and change the private enums to InputOutputModuleView(text: """ [interactive-element id=1]Some interactive element text[/interactive-element] different text[interactive-element id=1]more interactive element text[/interactive-element] """)
> fix: Remove leading space in interactive element regex

- Source/Text Parsing/RichTextParser.swift
In order for Markdown tables to look nice we need to add hard breaks as an option in the markdown parser
Try out the following string before/after - there should be line breaks at least in the table even if it doesn't render properly
```
| Substance | [math]\\underline{S^{0} (\\frac{J}{mole K}}][/math] |
| --------- | --------------|
| [math]Na_2CO_3[/math] | 61.1 |
| [math]HCl(aq)[/math] | 56.5 |
| [math]NaCl(aq)[/math] | 115.5 |
| [math]H_2O[/math] | 70.0 |
| [math]CO_2(g)[/math] | 213.8 |
```
> fix: Add hard breaks to Markdown

- Example/Podfile.lock
- Podfile.lock
- Source/Extensions/StringExtension.swift
- UnitTests/Extensions/StringExtensionSpec.swift
- fixed StringExtension.split method in order to avoid out of bounds crash
> fix: fixed StringExtension.split method in order to avoid out of bounds crash

- Source/Delegates/RichTextViewDelegate.swift
- Source/View Generators/UITextViewGenerator.swift
- UnitTests/View Generators/UITextViewGeneratorSpec.swift
added optional method to protocol to use delegates canPerformAction method if it exists. 
> fix: update to extend uitextview

- greenkeeper.json
[GreenKeeper will be stopping operation in early June 2020](https://greenkeeper.io/), so we are migrating to GH's Dependabot for automated dependency management. This PR removes Greenkeeper's config, and an init PR for Dependabot is on the way.
Dependabot will only be enabled for the `website` directory since those updates won't affect RTV.
> chore: remove greenkeeper config

- Podfile.lock
- RichTextView.podspec
> fix: updating iOSMath library to fix crash

- Source/View Generators/UITextViewGenerator.swift
Disable accessibility for UITextView  if the input string is empty.
> fix: disable accessibility if input string is empty

- Source/Text Parsing/RichTextParser.swift
https://tophat.atlassian.net/browse/IOS-8619
Remove common editor tags so that markdown can be rendered within HTML tags.
Still Unknown:
- Unable to render block quotes (Markdown indents) with web FF on
Ask Kushal if you need some examples with HTML embedded with Markdown
> fix: Remove common editor tags before converting to HTML

- Source/Text Parsing/RichTextParser.swift
https://tophat.atlassian.net/browse/IOS-8669
> fix: Unescape HTML entities after converting from Markdown

- Source/View Generators/WKWebViewGenerator.swift
- UnitTests/View Generators/WKWebViewGeneratorSpec.swift
Added CC to show when playing inline videos from youtube. 
> fix: Add CC on inline videos 

- Package.swift
We now use better versioning of our iosMath fork in our Package.swift
> fix: Use better iosMath versioning in our Package.swift

- RichTextView.podspec
* Fixes Example app not building after #224.
> Fix Example app not building
